// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DashboardImport } from './routes/_dashboard'
import { Route as DashboardAppDashboardIndexImport } from './routes/_dashboard/app.dashboard/index'
import { Route as DashboardAppDashboardProjectListImport } from './routes/_dashboard/app.dashboard/project-list'
import { Route as DashboardAppDashboardProjectListIndexImport } from './routes/_dashboard/app.dashboard/project-list/index'
import { Route as DashboardAppDashboardProjectListProjectIdImport } from './routes/_dashboard/app.dashboard/project-list/$projectId'

// Create/Update Routes

const DashboardRoute = DashboardImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRoute,
} as any)

const DashboardAppDashboardIndexRoute = DashboardAppDashboardIndexImport.update(
  {
    path: '/app/dashboard/',
    getParentRoute: () => DashboardRoute,
  } as any,
)

const DashboardAppDashboardProjectListRoute =
  DashboardAppDashboardProjectListImport.update({
    path: '/app/dashboard/project-list',
    getParentRoute: () => DashboardRoute,
  } as any)

const DashboardAppDashboardProjectListIndexRoute =
  DashboardAppDashboardProjectListIndexImport.update({
    path: '/',
    getParentRoute: () => DashboardAppDashboardProjectListRoute,
  } as any)

const DashboardAppDashboardProjectListProjectIdRoute =
  DashboardAppDashboardProjectListProjectIdImport.update({
    path: '/$projectId',
    getParentRoute: () => DashboardAppDashboardProjectListRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/_dashboard/app/dashboard/project-list': {
      preLoaderRoute: typeof DashboardAppDashboardProjectListImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/app/dashboard/': {
      preLoaderRoute: typeof DashboardAppDashboardIndexImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/app/dashboard/project-list/$projectId': {
      preLoaderRoute: typeof DashboardAppDashboardProjectListProjectIdImport
      parentRoute: typeof DashboardAppDashboardProjectListImport
    }
    '/_dashboard/app/dashboard/project-list/': {
      preLoaderRoute: typeof DashboardAppDashboardProjectListIndexImport
      parentRoute: typeof DashboardAppDashboardProjectListImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  DashboardRoute.addChildren([
    DashboardAppDashboardProjectListRoute.addChildren([
      DashboardAppDashboardProjectListProjectIdRoute,
      DashboardAppDashboardProjectListIndexRoute,
    ]),
    DashboardAppDashboardIndexRoute,
  ]),
])
